### ISSUE TITLE
Make fabalicious output less nerdy

### ISSUE THREAD

**Issue by MuschPusch** [factorial-io/fabalicious#16]
@stmh What do you think about suppressing the command line output for regular humans and give information on a per task basis? Not sure if we can catch errors in a good way but for e.g. deployment the best thing would be:

* backup suceeded
* git rebase suceeded
* drush tasks succeeded
*  [...]

Here is some stackoverflow:
http://stackoverflow.com/questions/9456419/easy-way-to-suppress-output-of-fabric-run

**Comment by stmh** [comment]
Ok, I refactored the code to suppress most of the output and show it only when an error occurs. But the chances are high, that I broke something. Please review and test the dev-branch thoroughly.

**Comment by stmh** [comment]
Ok, I refactored the code to suppress most of the output and show it only when an error occurs. But the chances are high, that I broke something. Please review and test the dev-branch thoroughly.

**Comment by stmh** [comment]
Ok, I refactored the code to suppress most of the output and show it only when an error occurs. But the chances are high, that I broke something. Please review and test the dev-branch thoroughly.

**Comment by stmh** [comment]
Ok, I refactored the code to suppress most of the output and show it only when an error occurs. But the chances are high, that I broke something. Please review and test the dev-branch thoroughly.

**Comment by stmh** [comment]
Ok, I refactored the code to suppress most of the output and show it only when an error occurs. But the chances are high, that I broke something. Please review and test the dev-branch thoroughly.

**Comment by MuschPusch** [comment]
Nice! One thing which is tricky: 

Drush is now really quit. Since my memory can't take the 30 drush commands I like doing things like this: 

```fab config:mbb drush: | grep migrate```

Which is not possible anymore. Overwriting it globally would result it being in version control for us all or uncommitted but active on instances. What do you think about a fabfile.local.yaml where we could overwrite this on (hidden feature request) a per instance level without bothering e.g. the frontenders.

**Comment by stmh** [comment]
Thanks for the heads-up, forgot about the drush-task

I think hiding the output when running a drush** task** makes no sense. The drush-task should give you the exact output as running drush by hand on the specific host.

We should hide the output of running drush commands as ports of other tasks, though.

**Comment by stmh** [comment]
Hmm, there are still major flaws: 

* You don't get the output from failed tasks. 
* Also, when an command needs input from the prompt they'll sit there forever waiting.

**Comment by stmh** [comment]
Ok, back to start -- too much problems.

**Comment by stmh** [comment]
Part of 0.20.0. Needs more testing on master...
