### ISSUE TITLE
specify git branch to use while deploying

### ISSUE THREAD

**Issue by d34dman** [factorial-io/fabalicious#23]
Right now `fab config:myproject-staging deploy` will use the default branch to pull specified in `myproject-staging` in the `fabfile.yaml`.

Now if the developer wants to use staging server to test for a release branch or a hotfix branch, it would be convenient if we could choose a branch during deploy command. Something in the lines of 
`fab config:myproject-staging deploy:'--branch=hotfix/1.16.2'`

This enhancement is not critical because i can edit the fabfile.yaml directly whenever we need to change the branch.

**Comment by stmh** [comment]
part of fabalicious 2.0.
