### ISSUE TITLE
Connect to a remote instance using SeQuel Pro

### ISSUE THREAD

**Issue by d34dman** [factorial-io/fabalicious#26]
I tried following

`fab config:example.com docker:show_remote_access\,public_ip=127.0.0.1`

I received something like below as a response

`ssh -L127.0.0.1:8888:171.17.3.10:80 -p 22 username@example.com`

Executed it in a terminal.

But got a error message that "operation timed out".

More observations will be updated here.

**Comment by stmh** [comment]
The command is intended to show you hoy you can connect to the http-server inside the docker image. Please replace ":80" with ":3306". 

But there's another obstacle: mysql denies the connection because user root may only connect from localhost. This should be fixed in drupal-docker

**Comment by stmh** [comment]
Perhaps we can add a port-setting which defaults to 80

**Comment by stmh** [comment]
using the experimental 2.0 branch you should be able to create a ssh-tunnel to the inner mysql-instance via: 
```
fab config:<your-confg> docker:startRemoteAccess,port=3306,publicPort=33060
```

Then you should be able to connect to the database on `localhost:33060`
