### ISSUE TITLE
Cancelling install task on existing installation causes data loss

### ISSUE THREAD

**Issue by d34dman** [factorial-io/fabalicious#32]
If you run install command on existing installation, and then decide to cancel, by inputting 'n' when prompted, settings.php is deleted nevertheless.

    ElektronicsJunkyard: myproject [develop*] $ fab config:mbb install
    Fabalicious deployment scripts

    [myproject.dev] Executing task 'install'
    Installing fresh database for mbb
    Creating database
    You are about to create a sites/default/settings.php file and DROP all tables in your 'myproject' database. Do you want to continue? (y/n): n
    Cancelled.                                                              [cancel]

**Comment by stmh** [comment]
There's a Backup of the settings-file. No data loss, just rename it back.

**Comment by d34dman** [comment]
If I remember correctly there was no settings.php.old in defaults directory. No files directory either. Only default.settings.php. Will confirm when 
I get back to my place later today.

**Comment by d34dman** [comment]
ok just confirmed, yes... there is a settings.php.old file and i can revert it back manually.
