### ISSUE TITLE
getSQLDump and getFIilesDump use static temp directory

### ISSUE THREAD

**Issue by manuelbitmade** [factorial-io/fabalicious#58]
Both methods seem to ignore the `tmpFolder` setting in the hosts config. Backup paths are built using `/tmp` as the target directory. As far as I understand these 2 lines need to be changed in order to make the tasks work with dynamic paths.

https://github.com/factorial-io/fabalicious/blob/0d2051cd790e0c22d6de148a491821c7e7b5c755/fabfile.py#L171
https://github.com/factorial-io/fabalicious/blob/0d2051cd790e0c22d6de148a491821c7e7b5c755/fabfile.py#L188

Is this by design or should this use the `tmpFolder` setting?

**Comment by stmh** [comment]
Hi manuelbitmade,

Good catch,  you are right. Any chance you can provide a PR?

**Comment by manuelbitmade** [comment]
To be honest I've never written one line of Python code... 🙈
I can try to fix it myself but I'm sure you guys would be able to do it a lot faster 😄

**Comment by stmh** [comment]
Please test the fix on your end.

**Comment by manuelbitmade** [comment]
Hi @stmh,
I tested the fix and it the commands now correctly use the value set in `tmpFolder`.

However this did not fix the issue I'm having with a specific environment. Since this seems to be a different problem (maybe not even related to Fabalicious) I think this can be closed.

Thanks for your work.
